export const profile_page_types = {
  REQUEST_PROFILE_START: "REQUEST_PROFILE_START",
  REQUEST_PROFILE_SUCCESS: "REQUEST_PROFILE_SUCCESS",
  REQUEST_PROFILE_FAILURE: "REQUEST_PROFILE_FAILURE",

  UPDATE_PROFILE_START: "UPDATE_PROFILE_START",
  UPDATE_PROFILE_SUCCESS: "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "UPDATE_PROFILE_FAILURE",

  UPDATE_PROFILE_IMAGE_START: "UPDATE_PROFILE_IMAGE_START",
  UPDATE_PROFILE_IMAGE_SUCCESS: "UPDATE_PROFILE_IMAGE_SUCCESS",
  UPDATE_PROFILE_IMAGE_FAILURE: "UPDATE_PROFILE_IMAGE_FAILURE",
};
