export const post_types = {
  REQUEST_ALL_COMMENTS_START: "REQUEST_ALL_COMMENTS_START",
  REQUEST_ALL_COMMENTS_SUCCESS: "REQUEST_ALL_COMMENTS_SUCCESS",
  REQUEST_ALL_COMMENTS_FAILURE: "REQUEST_ALL_COMMENTS_FAILURE",
};
