export const investors_page_types = {
  REQUEST_TOP_INVESTORS_START: "REQUEST_TOP_INVESTORS_START",
  REQUEST_TOP_INVESTORS_SUCCESS: "REQUEST_TOP_INVESTORS_SUCCESS",
  REQUEST_TOP_INVESTORS_FAILURE: "REQUEST_TOP_INVESTORS_FAILURE",
};
