export const articles_page_types = {
  REQUEST_UNFILTERED_ARTICLES_START: "REQUEST_UNFILTERED_ARTICLES_START",
  REQUEST_UNFILTERED_ARTICLES_SUCCESS: "REQUEST_UNFILTERED_ARTICLES_SUCCESS",
  REQUEST_UNFILTERED_ARTICLES_FAILURE: "REQUEST_UNFILTERED_ARTICLES_FAILURE",
  REQUEST_MORE_UNFILTERED_ARTICLES_START:
    "REQUEST_MORE_UNFILTERED_ARTICLES_START",
  REQUEST_MORE_UNFILTERED_ARTICLES_SUCCESS:
    "REQUEST_MORE_UNFILTERED_ARTICLES_SUCCESS",
  REQUEST_MORE_UNFILTERED_ARTICLES_FAILURE:
    "REQUEST_MORE_UNFILTERED_ARTICLES_FAILURE",
  REQUEST_FILTERED_ARTICLES_START: "REQUEST_FILTERED_ARTICLES_START",
  REQUEST_FILTERED_ARTICLES_SUCCESS: "REQUEST_FILTERED_ARTICLES_SUCCESS",
  REQUEST_FILTERED_ARTICLES_FAILURE: "REQUEST_FILTERED_ARTICLES_FAILURE",
  REQUEST_MORE_FILTERED_ARTICLES_START: "REQUEST_MORE_FILTERED_ARTICLES_START",
  REQUEST_MORE_FILTERED_ARTICLES_SUCCESS:
    "REQUEST_MORE_FILTERED_ARTICLES_SUCCESS",
  REQUEST_MORE_FILTERED_ARTICLES_FAILURE:
    "REQUEST_MORE_FILTERED_ARTICLES_FAILURE",
  STORE_LAST_FILTERED_ARTICLE: "STORE_LAST_FILTERED_ARTICLE",
  STORE_LAST_UNFILTERED_ARTICLE: "STORE_LAST_UNFILTERED_ARTICLE",
  REQUEST_CATEGORIES_START: "REQUEST_CATEGORIES_START",
  REQUEST_CATEGORIES_SUCCESS: "REQUEST_CATEGORIES_SUCCESS",
  REQUEST_CATEGORIES_FAILURE: "REQUEST_CATEGORIES_FAILURE",
  SELECT_CATEGORY: "SELECT_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",
  NO_MORE_UNFILTERED_ARTICLES: "NO_MORE_UNFILTERED_ARTICLES",
  NO_MORE_FILTERED_ARTICLES: "NO_MORE_FILTERED_ARTICLES",
};
