export const write_page_types = {
  UPLOAD_DRAFT_START: "UPLOAD_DRAFT_START",
  UPLOAD_DRAFT_SUCCESS: "UPLOAD_DRAFT_SUCCESS",
  UPLOAD_DRAFT_FAILURE: "UPLOAD_DRAFT_FAILURE",
  UPLOAD_ARTICLE_START: "UPLOAD_ARTICLE_START",
  UPLOAD_ARTICLE_SUCCESS: "UPLOAD_ARTICLE_SUCCESS",
  UPLOAD_ARTICLE_FAILURE: "UPLOAD_ARTICLE_FAILURE",
  CREATE_DRAFT_START: "CREATE_DRAFT_START",
  CREATE_DRAFT_SUCCESS: "CREATE_DRAFT_SUCCESS",
  CREATE_DRAFT_FAILURE: "CREATE_DRAFT_FAILURE",
};
