export const investor_page_types = {
  REQUEST_INDIVIDUAL_TRADES_START: "REQUEST_INDIVIDUAL_TRADES_START",
  REQUEST_INDIVIDUAL_TRADES_SUCCESS: "REQUEST_INDIVIDUAL_TRADES_SUCCESS",
  REQUEST_INDIVIDUAL_TRADES_FAILURE: "REQUEST_INDIVIDUAL_TRADES_FAILURE",

  REQUEST_INDIVIDUAL_POSTS_START: "REQUEST_INDIVIDUAL_POSTS_START",
  REQUEST_INDIVIDUAL_POSTS_SUCCESS: "REQUEST_INDIVIDUAL_POSTS_SUCCESS",
  REQUEST_INDIVIDUAL_POSTS_FAILURE: "REQUEST_INDIVIDUAL_POSTS_FAILURE",

  REQUEST_INVESTOR_PROFILE_START: "REQUEST_INVESTOR_PROFILE_START",
  REQUEST_INVESTOR_PROFILE_SUCCESS: "REQUEST_INVESTOR_PROFILE_SUCCESS",
  REQUEST_INVESTOR_PROFILE_FAILURE: "REQUEST_INVESTOR_PROFILE_FAILURE",

  REQUEST_USER_ARTICLES_START: "REQUEST_USER_ARTICLES_START",
  REQUEST_USER_ARTICLES_SUCCESS: "REQUEST_USER_ARTICLES_SUCCESS",
  REQUEST_USER_ARTICLES_FAILURE: "REQUEST_USER_ARTICLES_FAILURE",
};
