export const home_page_types = {
  REQUEST_LATEST_TRADES_START: "REQUEST_LATEST_TRADES_START",
  REQUEST_LATEST_TRADES_SUCCESS: "REQUEST_LATEST_TRADES_SUCCESS",
  REQUEST_LATEST_TRADES_FAILURE: "REQUEST_LATEST_TRADES_FAILURE",
};
