export const homePageTypes = {
  FETCH_ARTICLES_START: "FETCH_ARTICLES_START",
  FETCH_ARTICLES_SUCCESS: "FETCH_ARTICLES_SUCCESS",
  FETCH_ARTICLES_FAILURE: "FETCH_ARTICLES_FAILURE",
  FETCH_COLLECTION_START: "FETCH_COLLECTION_START",
  FETCH_COLLECTION_SUCCESS: "FETCH_COLLECTION_SUCCESS",
  FETCH_COLLECTION_FAILURE: "FETCH_COLLECTION_FAILURE",
  FETCH_MORE_ARTICLES_START: "FETCH_MORE_ARTICLES_SUCCESS",
  FETCH_MORE_ARTICLES_SUCCESS: "FETCH_MORE_ARTICLES_SUCCESS",
  FETCH_MORE_ARTICLES_FAILURE: "FETCH_MORE_ARTICLES_FAILURE",
};
