export const homePageTypes = {
  FETCH_UNFILTERED_ARTICLES_START: "FETCH_UNFILTERED_ARTICLES_START",
  FETCH_UNFILTERED_ARTICLES_SUCCESS: "FETCH_UNFILTERED_ARTICLES_SUCCESS",
  FETCH_UNFILTERED_ARTICLES_FAILURE: "FETCH_UNFILTERED_ARTICLES_FAILURE",
  FETCH_MORE_UNFILTERED_ARTICLES_START: "FETCH_MORE_UNFILTERED_ARTICLES_START",
  FETCH_FILTERED_ARTICLES_START: "FETCH_FILTERED_ARTICLES_START",
  FETCH_FILTERED_ARTICLES_SUCCESS: "FETCH_FILTERED_ARTICLES_SUCCESS",
  FETCH_FILTERED_ARTICLES_FAILURE: "FETCH_FILTERED_ARTICLES_FAILURE",
  FETCH_MORE_FILTERED_ARTICLES_START: "FETCH_MORE_FILTERED_ARTICLES_START",
  STORE_LAST_FILTERED_ELEMENT: "STORE_LAST_FILTERED_ELEMENT",
  STORE_AVAILABLE_TAGS_START: "STORE_AVAILABLE_TAGS_START",
  STORE_AVAILABLE_TAGS_SUCCESS: "STORE_AVAILABLE_TAGS_SUCCESS",
  STORE_AVAILABLE_TAGS_FAILURE: "STORE_AVAILABLE_TAGS_FAILURE",
};
