export const user_page_types = {
  REQUEST_USER_START: "REQUEST_USER_START",
  REQUEST_USER_SUCCESS: "REQUEST_USER_SUCCESS",
  REQUEST_USER_FAILURE: "REQUEST_USER_FAILURE",

  REQUEST_USER_RECOMMENDED_START: "REQUEST_USER_RECOMMENDED_START",
  REQUEST_USER_RECOMMENDED_SUCCESS: "REQUEST_USER_RECOMMENDED_SUCCESS",
  REQUEST_USER_RECOMMENDED_FAILURE: "REQUEST_USER_RECOMMENDED_FAILURE",

  REQUEST_USER_POSTS_START: "REQUEST_USER_POSTS_START",
  REQUEST_USER_POSTS_SUCCESS: "REQUEST_USER_POSTS_SUCCESS",
  REQUEST_USER_POSTS_FAILURE: "REQUEST_USER_POSTS_FAILURE",

  REQUEST_USER_REVIEWS_START: "REQUEST_USER_REVIEWS_START",
  REQUEST_USER_REVIEWS_SUCCESS: "REQUEST_USER_REVIEWS_SUCCESS",
  REQUEST_USER_REVIEWS_FAILURE: "REQUEST_USER_REVIEWS_FAILURE",

  REQUEST_MORE_USER_RECOMMENDED_START: "REQUEST_MORE_USER_RECOMMENDED_START",
  REQUEST_MORE_USER_RECOMMENDED_SUCCESS:
    "REQUEST_MORE_USER_RECOMMENDED_SUCCESS",
  REQUEST_MORE_USER_RECOMMENDED_FAILURE:
    "REQUEST_MORE_USER_RECOMMENDED_FAILURE",

  REQUEST_MORE_USER_POSTS_START: "REQUEST_MORE_USER_POSTS_START",
  REQUEST_MORE_USER_POSTS_SUCCESS: "REQUEST_MORE_USER_POSTS_SUCCESS",
  REQUEST_MORE_USER_POSTS_FAILURE: "REQUEST_MORE_USER_POSTS_FAILURE",

  REQUEST_MORE_USER_REVIEWS_START: "REQUEST_MORE_USER_REVIEWS_START",
  REQUEST_MORE_USER_REVIEWS_SUCCESS: "REQUEST_MORE_USER_REVIEWS_SUCCESS",
  REQUEST_MORE_USER_REVIEWS_FAILURE: "REQUEST_MORE_USER_REVIEWS_FAILURE",

  VALIDATE_SUBSCRIBER_START: "VALIDATE_SUBSCRIBER_START",
  VALIDATE_SUBSCRIBER_SUCCESS: "VALIDATE_SUBSCRIBER_SUCCESS",
  VALIDATE_SUBSCRIBER_FAILURE: "VALIDATE_SUBSCRIBER_FAILURE",

  NO_MORE_USER_POSTS: "NO_MORE_USER_POSTS",
  NO_MORE_USER_RECOMMENDED: "NO_MORE_USER_RECOMMENDED",
  NO_MORE_USER_REVIEWS: "NO_MORE_USER_REVIEWS",
};
