export const user_types = {
  LOG_IN_ACTIVE_USER_START: "LOG_IN_ACTIVE_USER_START",
  LOG_IN_ACTIVE_USER_SUCCESS: "LOG_IN_ACTIVE_USER_SUCCESS",
  LOG_IN_ACTIVE_USER_FAILURE: "LOG_IN_ACTIVE_USER_FAILURE",
  LOG_OUT_ACTIVE_USER_START: "LOG_OUT_ACTIVE_USER_START",
  LOG_OUT_ACTIVE_USER_SUCCESS: "LOG_OUT_ACTIVE_USER_SUCCESS",
  LOG_OUT_ACTIVE_USER_FAILURE: "LOG_OUT_ACTIVE_USER_FAILURE",
};
