export const user_types = {
  STORE_ACTIVE_USER_START: "STORE_ACTIVE_USER_START",
  STORE_ACTIVE_USER_SUCCESS: "STORE_ACTIVE_USER_SUCCESS",
  STORE_ACTIVE_USER_FAILURE: "STORE_ACTIVE_USER_FAILURE",
};
