export const dashboards_types = {
  CURRENT_DROPDOWN_SELECTION_TRADE: "CURRENT_DROPDOWN_SELECTION_TRADE",
  CURRENT_DROPDOWN_SELECTION_POST: "CURRENT_DROPDOWN_SELECTION_POST",

  CREATE_TRADE_CARD_START: "CREATE_TRADE_CARD_START",
  CREATE_TRADE_CARD_SUCCESS: "CREATE_TRADE_CARD_SUCCESS",
  CREATE_TRADE_CARD_FAILURE: "CREATE_TRADE_CARD_FAILURE",

  CREATE_POST_CARD_START: "CREATE_POST_CARD_START",
  CREATE_POST_CARD_SUCCESS: "CREATE_POST_CARD_SUCCESS",
  CREATE_POST_CARD_FAILURE: "CREATE_POST_CARD_FAILURE",
};
